-- MySQL Script generated by MySQL Workbench
-- Sun Oct 28 22:06:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema quanlicuusv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quanlicuusv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quanlicuusv` DEFAULT CHARACTER SET utf8 ;
USE `quanlicuusv` ;

-- -----------------------------------------------------
-- Table `quanlicuusv`.`bangkhaosat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlicuusv`.`bangkhaosat` (
  `bangID` INT(11) NOT NULL AUTO_INCREMENT,
  `tenbang` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`bangID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlicuusv`.`tinh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlicuusv`.`tinh` (
  `tinhID` INT(11) NOT NULL AUTO_INCREMENT,
  `tentinh` VARCHAR(255) NOT NULL,
  `kichhoat` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`tinhID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlicuusv`.`huyen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlicuusv`.`huyen` (
  `huyenID` INT(11) NOT NULL AUTO_INCREMENT,
  `tenhuyen` VARCHAR(255) NOT NULL,
  `tinhID` INT(11) NOT NULL,
  `kichhoat` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`huyenID`),
  INDEX `tinhID` (`tinhID` ASC)  ,
  CONSTRAINT `huyen_ibfk_1`
    FOREIGN KEY (`tinhID`)
    REFERENCES `quanli	cuusv`.`tinh` (`tinhID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlicuusv`.`khoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlicuusv`.`khoa` (
  `khoaID` INT(11) NOT NULL AUTO_INCREMENT,
  `tenkhoa` VARCHAR(255) NULL DEFAULT NULL,
  `kichhoat` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`khoaID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlicuusv`.`lop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlicuusv`.`lop` (
  `lopID` INT(11) NOT NULL AUTO_INCREMENT,
  `tenlop` VARCHAR(255) NOT NULL,
  `nganh` VARCHAR(255) NOT NULL,
  `khoaID` INT(11) NOT NULL,
  `kichhoat` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`lopID`),
  INDEX `khoaID` (`khoaID` ASC)  ,
  CONSTRAINT `lop_ibfk_1`
    FOREIGN KEY (`khoaID`)
    REFERENCES `quanlicuusv`.`khoa` (`khoaID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlicuusv`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlicuusv`.`user` (
  `userID` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` SET('admin', 'user', 'superadmin') NULL DEFAULT 'user',
  PRIMARY KEY (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlicuusv`.`cuusv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlicuusv`.`cuusv` (
  `csvID` INT(11) NOT NULL AUTO_INCREMENT,
  `hoten` VARCHAR(255) NOT NULL,
  `ngaysinh` DATE NOT NULL,
  `huyenID` INT(11) NULL DEFAULT NULL,
  `lopID` INT(11) NULL DEFAULT NULL,
  `sdt` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `anh` VARCHAR(255) NULL DEFAULT NULL,
  `userID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`csvID`),
  INDEX `huyenID` (`huyenID` ASC)  ,
  INDEX `lopID` (`lopID` ASC)  ,
  INDEX `userID` (`userID` ASC)  ,
  CONSTRAINT `cuusv_ibfk_1`
    FOREIGN KEY (`huyenID`)
    REFERENCES `quanlicuusv`.`huyen` (`huyenID`),
  CONSTRAINT `cuusv_ibfk_2`
    FOREIGN KEY (`lopID`)
    REFERENCES `quanlicuusv`.`lop` (`lopID`),
  CONSTRAINT `cuusv_ibfk_3`
    FOREIGN KEY (`userID`)
    REFERENCES `quanlicuusv`.`user` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlicuusv`.`coquan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlicuusv`.`coquan` (
  `coquanID` INT(11) NOT NULL AUTO_INCREMENT,
  `ten` VARCHAR(255) NOT NULL,
  `diachi` VARCHAR(255) NOT NULL,
  `loaihinh` ENUM('nhanuoc', 'tunhan', 'nuocngoai') NOT NULL,
  PRIMARY KEY (`coquanID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlicuusv`.`congtac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlicuusv`.`congtac` (
  `csvID` INT(11) NOT NULL,
  `ngaybatdau` DATE NOT NULL,
  `ngayketthuc` DATE NULL DEFAULT NULL,
  `coquanID` INT(11) NOT NULL,
  `vitri` VARCHAR(255) NOT NULL,
  `mucluong` INT(11) NOT NULL,
  `nganh` VARCHAR(255) NOT NULL,
  INDEX `csvID` (`csvID` ASC)  ,
  INDEX `coquanID` (`coquanID` ASC)  ,
  CONSTRAINT `congtac_ibfk_1`
    FOREIGN KEY (`csvID`)
    REFERENCES `quanlicuusv`.`cuusv` (`csvID`),
  CONSTRAINT `congtac_ibfk_2`
    FOREIGN KEY (`coquanID`)
    REFERENCES `quanlicuusv`.`coquan` (`coquanID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlicuusv`.`khaosat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlicuusv`.`khaosat` (
  `khaosatID` INT(11) NOT NULL AUTO_INCREMENT,
  `cauhoi` VARCHAR(255) NOT NULL,
  `luachon` SET('co', 'khonghoantoan', 'khong') NULL DEFAULT NULL,
  `csvID` INT(11) NOT NULL,
  `bangID` INT(11) NOT NULL,
  PRIMARY KEY (`khaosatID`),
  INDEX `csvID` (`csvID` ASC)  ,
  INDEX `bangID` (`bangID` ASC)  ,
  CONSTRAINT `khaosat_ibfk_1`
    FOREIGN KEY (`csvID`)
    REFERENCES `quanlicuusv`.`cuusv` (`csvID`),
  CONSTRAINT `khaosat_ibfk_2`
    FOREIGN KEY (`bangID`)
    REFERENCES `quanlicuusv`.`bangkhaosat` (`bangID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
